import React from "react"

const CustomHead: React.VFC = () => {
    return (
        <head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            {/* <link rel="icon" href="/favicon.ico" /> */}
        </head>
    )
}

export default CustomHead